### ISSUE TITLE
typo: humain being from -> human being from

### ISSUE THREAD

**Issue by Z4ck404** [slimaneakalie/slimane.io#21]
Typo here I think : https://github.com/slimaneakalie/slimane.io/blob/a9d16038034b5eef06570fb95abcfdabd7041b2d/pages/about.tsx#L44 unless it's there on purpose. Otherwise keep up the good work 👏

**Comment by slimaneakalie** [comment]
Thanks a lot @Z4ck404 for noticing the typo, it's fixed now
